#FROM rootproject/root-ubuntu16:latest
FROM ubuntu:16.04

# Samtools v1.9
#FROM fingerfen/samtools:latest

MAINTAINER Nhat Duong <duongn@email.chop.edu>

RUN apt-get update && apt-get install -y bzip2 gcc g++ make python zlib1g-dev wget git-all


# set environment

# install manta

RUN wget https://root.cern/download/root_v6.16.00.Linux-ubuntu18-x86_64-gcc7.3.tar.gz && \
        tar xfz root_v6.16.00.Linux-ubuntu18-x86_64-gcc7.3.tar.gz && \
	rm root_v6.16.00.Linux-ubuntu18-x86_64-gcc7.3.tar.gz


#RUN wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 && \
#	tar jxf samtools-1.9.tar.bz2 && \
#	rm samtools-1.9.tar.bz2 && \
#	cd samtools-1.9 && \
#	./configure --prefix $(pwd) && \
#	make && \
#	ln -s /usr/src/samtools-1.9/samtools /usr/bin/samtools


# && export ROOTSYS=$HOME/root \
# && export PATH=$PATH:$ROOTSYS/bin \
# && git clone https://github.com/abyzovlab/CNVnator.git

